accountapp/urls.py
# 하위 분기문 작성
# views.py에서 만든 helloworld를 보여주는 거
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    # 가운데가 함수 들어와야할 자린데 class가 들어가서 class의 함수를 뱉어주는 .as_view() 사용 (Class Based View 사용 위해서 사용해야댐)
    path('create/', AccountCreateView.as_view(), name='create'),
    # DetailView여서 primary_key인 id인 주소를 넘겨주어야 거기로 라우팅을 연결할 수 있다. ex) accountapp/detail/1/
    path('detail/<int:pk>/', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>/', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>/', AccountDeleteView.as_view(), name='delete'),

]

gis_2ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    # accountapp 으로 가는 추가적인 분기문 작성
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    # writer == user
    # ForeginKey : user가 게시물을 하나만 쓰는게 아니라 1:N인 ForeignKey를 사용. (1:1이면 OneToOne)
    # on_delete=models.SET_NULL : user가 계정삭제해도 게시물은 사라지지않음. (반대로 CASCADE는 다 사라짐)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)

    # image는 media/profile/aritcle/ 경로에 업로드 한다.
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    # 자동으로 날짜 입력되게, 날짜정보
    created_at = models.DateField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld
from articleapp.models import Article


# @login_required(login_url=reverse_lazy('accountapp:login')) # 장고에 이미 있는 데코레이터
# def hello_world(request):
#
#     if request.user.is_authenticated:
#
#         if request.method == "POST":
#
#             temp = request.POST.get('input')
#
#             new_data = HelloWorld()
#             new_data.text = temp
#             new_data.save()
#
#             return HttpResponseRedirect(reverse('accountapp:hello_world'))
#
#         else:
#             data_list = HelloWorld.objects.all()
#             return render(request, 'accountapp/hello_world.html', context={'data_list': data_list})
#
#     else:
#         return HttpResponseRedirect(reverse('accountapp:login'))


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # success_url = reverse_lazy('accountapp:hello_world') # 성공하면 hello_world로 가라!, # 만들고 추가하는거라 success~ 해줬음
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

# DetailView
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user' # 컨텍스트에서 볼 객체의 이름 설정?
    template_name = 'accountapp/detail.html'

    paginate_by = 20

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list,
                                        **kwargs)

# 데코레이터 요소 리스트 (그냥 중복 줄이려고)
has_ownership = [account_ownership_required, login_required]

# 장고에 이미 있는 데코레이터 적용
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User # 기존 AccountCreateView와 동일한 모델 값을 사용해요.
    form_class = AccountCreationForm # form을 만들어 값을 전달하게 되요. (ID변경 막으려고, 커스터마이징한 Form을 새로 만들어 전달받아 사용.)
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list') # 성공적으로 프로필이 완성되면 메인화면으로 넘겨줍니다.
    template_name = 'accountapp/update.html' # template경로 값을 지정해줘요.


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit", class="btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <!-- form태그의 action 속성의 값에 pk=user.pk를 적어야, 이전 url에서 받아온 <int:pk>가 방금 적은 값으로 할당 -->
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit", class="btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{# 부트스트랩은 필요 없음 #}
{# {% load bootstrap4 %} #}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>{{ target_user.username }}</h4>
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>

        <!-- Profile 부분 -->
        {# 여기서 profile은 model에서 related_name=profile 이거다. #}
        {% if target_user.profile %}
        <div>
            <img src="{{ target_user.profile.image.url }}" alt="profile image"
                 class="profile_image m-4">
            <h2 class="NNS_B">
                {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                       class="material-icons round_button">
                        edit
                    </a>
                    {% endif %}
            </h2>
            <h5>{{ target_user.profile.message }}</h5>
        {% else %}
            <a href="{% url 'profileapp:create' %}"><h5>Create Profile</h5></a>
        </div>
        {% endif %}

        <!-- 현재 target_user와 DB에 있는 user가 동일한지! 확인 -->
        {% if target_user == user %}
        <div class="text-center">
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                settings
            </a>
        </div>
        <div class="text-center">
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                close
            </a>
        </div>
        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{##}
{#    <div style="margin: 2rem; text-align: center">#}
{#        <h1>METHOD</h1>#}
{##}
{#        <form action="/accounts/hello_world/" method="post">#}
            {# 장고에서 정상적으로 post 사용하려면 #}
{#            {% csrf_token %}#}
{#            <input type="text" name="input">#}
{#            <input type="submit" class="btn btn-dark rounded-pill px-5">#}
{#        </form>#}
{##}
{#        {% for data in data_list %}#}
            {# 단순 변수 출력 : {{  }} #}
{#            <h3>{{ data.text }}</h3>#}
{#        {% endfor %}#}
{##}
{#    </div>#}
{##}
{##}
{#{% endblock %}#}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit", class="btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            <!-- form태그의 action 속성의 값에 pk=user.pk를 적어야, 이전 url에서 받아온 <int:pk>가 방금 적은 값으로 할당 -->
            <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit", class="btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}