articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'articleapp'

urlpatterns = [
    # path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

gis_2ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    # accountapp 으로 가는 추가적인 분기문 작성
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    # writer == user
    # ForeginKey : user가 게시물을 하나만 쓰는게 아니라 1:N인 ForeignKey를 사용. (1:1이면 OneToOne)
    # on_delete=models.SET_NULL : user가 계정삭제해도 게시물은 사라지지않음. (반대로 CASCADE는 다 사라짐)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)

    # image는 media/profile/aritcle/ 경로에 업로드 한다.
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    # 자동으로 날짜 입력되게, 날짜정보
    created_at = models.DateField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

templates/snippets/list_fragment.html
{% load static %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
          width: 45%;
          max-width: 200px;
          {#height: 500px;#}
          {#background-color: antiquewhite;#}
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
          flex-direction: column;
          box-shadow: 0 0 1rem gray;

        }

        .container img {
            width: 100%;
            border-radius: 1rem;
        }

    </style>

    <div class="container my-4">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="my-2 NNS_B">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

templates/snippets/pagination.html
<div class="text-center my-5">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="btn btn-secondary rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
    {% endif %}
        <a href="#"
           class="btn btn-dark rounded-pill">
            {{ page_obj.number }}
        </a>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn btn-secondary rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
    {% endif %}
</div>