accountapp/urls.py
# 하위 분기문 작성
# views.py에서 만든 helloworld를 보여주는 거
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    # 가운데가 함수 들어와야할 자린데 class가 들어가서 class의 함수를 뱉어주는 .as_view() 사용 (Class Based View 사용 위해서 사용해야댐)
    path('create/', AccountCreateView.as_view(), name='create'),
    # DetailView여서 primary_key인 id인 주소를 넘겨주어야 거기로 라우팅을 연결할 수 있다. ex) accountapp/detail/1/
    path('detail/<int:pk>/', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>/', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>/', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'articleapp'

urlpatterns = [
    # path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

gis_2ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    # accountapp 으로 가는 추가적인 분기문 작성
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body style="font-family: 'NanumSquareR'">

{% include 'header.html' %}

<hr>

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
    {#내용 들어가는 부분#}
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center">

    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>Pragmatic</h5>
    </div>

</div>

templates/head.html
{# css 받아오기 #}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    {# BootStrap Link #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#    Google Fonts Link #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">

    {#  Defalut CSS Link  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    {# 나눔폰트 가져오기  #}
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">

    <div class="pragmatic_header_logo">
        <h1><a href="{% url 'home' %}"
               style="color: black">KickBack</a></h1>
    </div>
    <div class="pragmatic_header_button">
        <span class="mx-2">
            <a href="{% url 'articleapp:list' %}">
                Articles
            </a>
        </span>

        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">
                Projects
            </a>
        </span>

        {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'subscribeapp:list' %}">
                Subscription
            </a>
        </span>
        {% endif %}

{#        유저가 로그인 해있는지 안해있는지 판별하는 분기분#}
        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">
                Login
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">
                Sign Up
            </a>
        </span>
        {% else %}
        <span class="mx-2">
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                MyPage
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>
        {% endif %}
    </div>

</div>