articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'articleapp'

urlpatterns = [
    # path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

gis_2ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    # accountapp 으로 가는 추가적인 분기문 작성
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    # writer == user
    # ForeginKey : user가 게시물을 하나만 쓰는게 아니라 1:N인 ForeignKey를 사용. (1:1이면 OneToOne)
    # on_delete=models.SET_NULL : user가 계정삭제해도 게시물은 사라지지않음. (반대로 CASCADE는 다 사라짐)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)

    # image는 media/profile/aritcle/ 경로에 업로드 한다.
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    # 자동으로 날짜 입력되게, 날짜정보
    created_at = models.DateField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

articleapp/forms.py
from django import forms
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'min-height: 10rem;'
                                                                    'text-align: left;'}))

    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    # success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        # temp_article = form.save(commit=False)
        # temp_article.writer = self.request.user
        # temp_article.save()
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'

    def get_success_url(self):
        return reverse('articleapp:list')


# 여러개의 게시글을 한번에 보여주는 멀티객체인 ListView사용
class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20 # 페이징화화

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Create Article</h4>
        </div>
        <div>
            <!-- article에는 image가 들어가기 때문에 enctype을 설정해준다. -->
            <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit", class="btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

    {# WYSIWYG, medium-ediotr #}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">

    <script>var editor = new MediumEditor('.editable');</script>


{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Delete Article : {{ target_article.title }}</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit"
                        class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container text-center">
        <div class="my-5">
            {# 게시글 제목, 좋아요, 글쓴이, 작성일자 #}
            <h1 class="NNS_B">{{ target_article.title }}</h1>
            <div class="my-3">
                <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}"
                    class="material-icons"
                    style="vertical-align: middle; font-size: 1.4rem; color: #f77;">
                    favorite
                </a>
                <span style="vertical-align: middle">
                    {{ target_article.like }}
                </span>
{#                <span class="material-icons" style="vertical-align: middle; font-size: 1.4rem;">#}
{#                    comment#}
{#                </span>#}
{#                <span style="vertical-align: middle">{{ target_article.comment.count }}</span>#}
            </div>
            <h4>{{ target_article.writer.profile.nickname }}</h4>
            <p>{{ target_article.created_at }}</p>
        </div>

        <hr>

        <div>
            {# 게시글 내용, 게시글 대표 이미지 #}
            <img src="{{ target_article.image.url }}"
                 class="article_image" alt="">
            <div class="article_content my-5">{{ target_article.content | safe }}</div>
            {% if target_article.writer == user %}
            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                   class="btn btn-success rounded-pill px-5">
                    Update
                </a>
                <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
                    class="btn btn-danger rounded-pill px-5">
                    Delete
                </a>
            </div>
            {% endif %}

            <hr>

            <div class="text-center my-4">
                {# 댓글 작성 폼 및 댓글 #}

                {% for comment in target_article.comment.all %}
                    <div class="comment_box">
                        <div>
                            <span>
                                <img src="{{ comment.writer.profile.image.url }}" alt="profile image"
                                     class="comment_image m-2">
                            </span>
                            <span class="NNS_B" style="font-size: 1.4rem">{{ comment.writer.profile.nickname }}</span>
                            <span>{{ comment.created_at }}</span>
                        </div>
                        <br>
                        <div>
                            <p>{{ comment.content }}</p>
                        </div>
                        {% if comment.writer == user %}
                        <div style="text-align: right">
                            <a href="{% url 'commentapp:delete' pk=comment.pk %}"
                               class="btn btn-danger rounded-pill px-5">
                                Delete
                            </a>
                        </div>
                        {% endif %}
                    </div>
                {% endfor %}



{#                {% include 'commnetapp/create.html' with article=target_article %} 블로그에는 이렇게 나와있음 뭔차이일까? #}
                {% include 'commentapp/create.html' %}
            </div>

        </div>
    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
          width: 45%;
          max-width: 200px;
          {#height: 500px;#}
          {#background-color: antiquewhite;#}
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
          flex-direction: column;
          box-shadow: 0 0 1rem gray;

        }

        .container img {
            width: 100%;
            border-radius: 1rem;
        }

    </style>

    <div class="container my-4">
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="my-2 NNS_B">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

{#    <div class="container">#}
{#      <div class="item1">#}
{#        <img src="https://picsum.photos/200/300">#}
{#      </div>#}
{#      <div class="item2">#}
{#        <img src="https://picsum.photos/200/340">#}
{#      </div>#}
{#      <div class="item3">#}
{#        <img src="https://picsum.photos/200/280">#}
{#      </div>#}
{#      <div class="item4">#}
{#        <img src="https://picsum.photos/200/390">#}
{#      </div>#}
{#      <div class="item5">#}
{#        <img src="https://picsum.photos/200/200">#}
{#      </div>#}
{#      <div class="item6">#}
{#        <img src="https://picsum.photos/200/500">#}
{#      </div>#}
{#      <div class="item7">#}
{#        <img src="https://picsum.photos/200/100">#}
{#      </div>#}
{#      <div class="item8">#}
{#        <img src="https://picsum.photos/200/250">#}
{#      </div>#}
{#      <div class="item9">#}
{#        <img src="https://picsum.photos/200/320">#}
{#      </div>#}
{#      <div class="item10">#}
{#        <img src="https://picsum.photos/200/300">#}
{#      </div>#}
{#      <div class="item11">#}
{#        <img src="https://picsum.photos/200/300">#}
{#      </div>#}
{#      <div class="item12">#}
{#        <img src="https://picsum.photos/200/270">#}
{#      </div>#}
{#      <div class="item13">#}
{#        <img src="https://picsum.photos/200/330">#}
{#      </div>#}
{#    </div>#}

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>


{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Article</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:update' pk=target_article.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit"
                        class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

    {# WYSIWYG, medium-ediotr #}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}